### ISSUE TITLE
Mac系统文件格式异常

### ISSUE THREAD

**Issue by JarlJreg** [dop-lm/CSTI-ModLoader#1]
在Mac系统上会因为路径格式使用的斜杠方向不同无法找到数据文件，生成FileNotFoundException

如下：FileNotFoundException: Could not find file "/Users/[username]/Library/Application Support/Steam/steamapps/common/Card Survival Tropical Island/BepInEx\plugins\TinderJar\CardData\TinderJarOn.json"

**Comment by dop-lm** [comment]
应该改好了，可以试试
